CREATE DATABASE IF NOT EXISTS gauth;

CREATE TABLE IF NOT EXISTS gauth.credentials (
    id VARCHAR(36) PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    salt VARCHAR(255) NOT NULL
);
