CREATE SCHEMA IF NOT EXISTS gauth;

CREATE TABLE IF NOT EXISTS gauth.credentials (
    id UUID PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    salt VARCHAR(255) NOT NULL
);
